### ISSUE TITLE
Can't find brush for: peoplecode confluence 5.9

### ISSUE THREAD

**Issue by mverselle** [markstramaglia/peoplecode-syntaxhighlighter-brush#4]
Hi Mark,

I noticed you had another ticket about confluence 5.9 and the brush not loading, but I am able to load the brush into confluence, but am getting another:  Can't find brush for: peoplecode

I am using the Version 1.0.2 listed on github.  Any ideas?

**Comment by markstramaglia** [comment]
Hi @mverselle, 

After working with Atlassian, they identified that the following workaround will allow the brush to work in Confluence:  https://jira.atlassian.com/browse/CONF-40325

After getting the brush file to load (it originally wouldn't load because the file I downloaded from GitHub had HTML in it.  I copied and pasted the text of the JS into a file and then that loaded fine), I performed the workaround steps below in my 5.9 environment and the macro is working again.

**WorkAround**

Manually downgrade the Code Block Macro plugin to version 2.1.7.
To downgrade the add-on, do the following:
1. Stop Confluence.
2. Locate the existing .jar files (newcode-macro-plugin-XXX.jar) in <confluence-install>/confluence/WEB-INF/atlassian-bundled-plugins/. Move the file to a different location to create a backup copy.
3. Place the newcode-macro-plugin-2.1.7.jar into the atlassian-bundled-plugins directory.
4. Locate the existing transformed .jar (newcode-macro-plugin-XXX_XXX) in <confluence-install>/plugins-osgi-cache/transformed-plugins/.Delete the file.
5. Start Confluence.

As with all recommendations, Atlassian strongly suggests testing this in a test environment prior to implementing in Production. If this causes other issues in your instance, you will be asked to switch back to the original version of the .jar.

**Comment by markstramaglia** [comment]
@mverselle please let me know if the workaround resolves the issue for you, and if so, we can close this issue.

Thanks,
Mark

**Comment by mverselle** [comment]
Hi Mark,

I was able to do this successfully on our Dev server, so I believe this workaround will fix the issue.  I will have to wait and schedule this on production, but I am confident if it works on my dev instance it will be fine in prod.

Please close this Issue, and thank you.
Michael
